### ISSUE TITLE
fix UI / UX

### ISSUE THREAD

**Issue by fam4r** [fablabromagna-org/Lemonade-OLD#10]
# Login
- [x] Bottone "Registrazione" -> "Registrati"

# Registrazione
- [x] Privacy policy e Termini di utilizzo non linkati

# Website
- [x] "Esci" -> "Disconnetti" vicino all'icona del profilo
- [x] Togliere quella banda nera, il pulsante esci può andare sopra, vicino al profilo (vedi sopra), per tornare alla dashboard puoi fare un link all'inizio della pagina (es. attività) "< torna alla Dashboard"
- [x] CSS, mettere 100vh (adattamento contenuto all'altezza dello schermo)
- [x] Migliorare colori
-  [x] [Footer] Togliere il testo giustificato. Inserire dati sociatari FLR, privacy policy, termini di utilizzo, informativa cookie (se li utilizzi)
- [x] [Session] Non c'è una scadenza alla sessione? Forever Logged? 

# Attività Svolte
- [x] "In questa pagina sono presenti tutte le attività che hai svolto all'interno di FabLab Romagna e ti sono state riconosciute." -> "Qui trovi le attività svolte presso FabLab Romagna e riconosciute dall'associazione."

# FabCoin
- [x] euro -> Euro
- [x] coni (?)
- [x] Borsello -> Wallet
- [x] "Il tuo saldo FabCoin è di 0." -> "Il tuo saldo è di 0 FabCoin."

# Dashboard
- [x] Presentare meglio i 3 contenuti
- [x] Non sei mai stato presente. -> hai 0 presenze.
- [x] Sei stato presente 2h 17m 3s. -> "Hai <n> presenze" (il totale ore si potrebbe mettere all'interno, fuori è brutto anche coi secondi)
- [ ] Non hai nessun FabCoin. -> hai X fabcoin. Scopri come spenderli!
- [x] Quando sei su Dashboard, togliere il pulsante "Dashboard"

# Impostazioni
- [ ] "contattare il supporto" (metti un link, magari un mailto o un form, per darmi la possibilità di farlo)
- [ ] "Categoria utente": "predefinito" (cosa vuol dire? quali sono i miei permessi/diritti?)
- [ ] [Profilo] "Se hai necessità" -> "Per"
- [ ] [Social] cosa vuol dire / che funzionalità mi dà la possibilità di collegarmi con i social network? manca twitter
- [ ] [Social] Sezione che può essere integrata come card dentro le impostazioni o direttamente dentro la card del profilo

# Mail
- [x] Fare meno padding nel titolo "FabLab Romagna" della mail
- [x] Se possibile, anziché mandare la mail con una nuova password, fare sistema per inserimento nuova password

**Comment by esavini** [comment]
La barra nera te la vedi solo con due bottoni ma è una questione di permessi, sarebbe presente anche ```Gestione```. In futuro ne sono previsti altri.
La password l'hai ricevuta via email perché te l'ho inviata io tramite il pannello di supporto, puoi modificarla nelle impostazioni.
Il template delle email non è integrato nel portale ma è una soluzione di FLR (che sistemerò).

**Comment by fam4r** [comment]
Update: inserita alla checklist issue sulla durata della sessione

**Comment by esavini** [comment]
La sessione dura un mese (cookie), in futuro aggiungerò anche la possibilità di utilizzare una sessione temporanea e di ridurre la durata per il proprio account nelle impostazioni.

**Comment by fam4r** [comment]
Update: inserito parere sul conteggio delle ore di attività in dashboard.

**Comment by esavini** [comment]
- Cambio "Esci" in "Log out" invece che "Disconnetti" per brevità
- Devo aggiungere una modalità per modificare il footer, vedrò in futuro, ora ho altre urgenze
- La privacy policy è un problema dell'associazione non del programma, tieni a mente che altri FabLab potrebbero tranquillamente installarsi il gestionale
- Per il supporto ci stiamo organizzando.
