### ISSUE TITLE
Gestione attività: committente / progetto

### ISSUE THREAD

**Issue by itarozzi** [fablabromagna-org/Lemonade-OLD#5]
Aggiungere i campi committente e progetto, selezionabili da lista, in modo da attribuire l'attività ad un progetto specifico

**Comment by esavini** [comment]
La gestione potrebbe essere unita con #4? Nel senso, si potrebbe usare un tag anche per i progetti.

**Comment by itarozzi** [comment]
In linea di massima direi di sì. L'utilizzo di un campo specifico potrebbe facilitare la ricerca (filtri avanzati) ma in prima battuta potrebbe bastare la tag (ammesso di poter attribuire tag multiple alle singole attività)

**Comment by esavini** [comment]
Sì, ovviamente un'attività potrà avere più tag.
Per riconoscerli al massimo si potrebbe fare come in GitHub (guarda come sono segnati alcune labels in questo progetto, è una pratica comune su GitHub).
