### ISSUE TITLE
Documentazione progetto totem

### ISSUE THREAD

**Issue by itarozzi** [fablabromagna-org/Lemonade-OLD#6]
Aggiungere documentazione API totem per l'inserimento automatico delle presenze

**Comment by esavini** [comment]
Ho appena finito di scrivere la documentazione delle API ([la trovi qui](https://github.com/98edoardo/FabLab-Romagna-Auth/wiki/API:-Totem-delle-presenze)).
La documentazione è più aggiornata rispetto al codice attualmente disponibile online ma conto di caricare l'aggiornamento entro questa sera.
