### ISSUE TITLE
Inserimento multiplo badge

### ISSUE THREAD

**Issue by itarozzi** [fablabromagna-org/Lemonade-OLD#7]
Possibilità di aggiungere badge multipli tramite importazione di file CSV o in alternativa tramite API (sviluppando poi un tool che prende un elenco CSV e lo processa con Post multipli)

**Comment by esavini** [comment]
Cosa intendi con inserimento multiplo? Ogni utente dovrebbe (è possibile aggiungerne più di uno ma non è una buona pratica) avere un solo badge. 
Anche perché ora che crei il CSV con identificativo del badge e l'utente a quale associarlo fai prima a seguire la procedura guidata online, no?

**Comment by itarozzi** [comment]
Ok 1 badge per ogni utente. Pensavo alla possibilità a regime, nel caso di molti utenti, di creare un elenco utente-nr badge da importare in un colpo solo, senza andare nella pagina di gestione del singolo utente e aggiungere il badge... Ma avrà senso quando effettivamente gli utenti da gestire saranno tanti. 

Oppure lasciamo perdere e facciamo in modo che ogni nuovo utente che si registra si va anche ad inserire i propri dati, badge compreso

**Comment by esavini** [comment]
E' una procedura che allungherebbe solo l'assegnazione, perché dovresti:

1. ricavare l'ID dell'utente;
2. inserirlo nel CSV;
3. ricavare l'ID della tessera (a mano leggendolo o tramite il lettore);
4. inserirlo nel CSV;
5. caricare il CSV.

Se per ogni utente invece lo si fa online, quando sei nel profilo dell'utente per vedere l'ID, aggiungi direttamente il badge.
