### ISSUE TITLE
Registrazione Nuovi Soci/Anagrafica Soci

### ISSUE THREAD

**Issue by Mau1955** [fablabromagna-org/Lemonade-OLD#9]
- [x] Nome
- [x] Cognome
- [x] email
- [x] Codice Fiscale
- [x] Data di Nascita
- [x] Luogo di Nascita
- [ ] Domicilio Abituale (Indirizzo Postale)

da riempire in automatico o a cura dello staff:

- [ ] Data/ora dell a richiesta di iscrizione
- [ ] Data delle accettazione del direttivo

E in un record figlio

- [ ] Annualità Pagamenti
- [ ] Pagmento avvenuto (flag)
- [ ] Modalità di pagamento (dominio chiuso: CC Postale, Carta Credito, Paypal, Bonifico, Contanti)

**Comment by Mau1955** [comment]
E poi anche lo spazio per una fotografia ...
e un record figlio con documenti allegati dal socio ...

**Comment by esavini** [comment]
Nome, cognome ed email sono già presenti nel sistema.
L'email può essere modificata soltanto dallo staff per evitare abusi del servizio.

Il codice fiscale e il luogo di nascita sono ridondanti se memorizzo il codice fiscale, sto già sviluppando questa parte. Il domicilio devo ancora inserirlo.

Tutta la parte di gestione del direttivo (e quindi delle domande per diventare socio) e dei pagamenti è in "stallo": la prima non è urgente (utilizziamo normalmente GSuite), per il secondo devo prima parlarne con il Presidente e il Tesoriere.

La fotografia è predisposta nell'interfaccia grafica ma l'utente non può inserirla (infatti è presente la figura anonima standard per tutti gli utenti), non è urgente.

**Comment by Mau1955** [comment]
La ridondanza serve a verificare se ci sono errori. Data e Luogo di nascita servono a verificare il codice fiscale. In ogni caso deve fare testo il codice fiscale, che ha al suo interno un codice di verifica di corretta digitazione.

**Comment by esavini** [comment]
La struttura del C.F. mi permette di evitare la ridondanza: sapendo nome e cognome controllo la validità del codice fiscale, se anche solo un dato è sbagliato il codice di controllo previsto è differente da quello indicato dall'utente e quindi blocco la procedura.

**EDIT:** In ogni caso la data di nascita è mostrata nel portale ma non viene memorizzata nel database.

**Comment by esavini** [comment]
Ho aggiunto la gestione delle anagrafiche principali: data di nascita, luogo di nascita, sesso e codice fiscale.

Tra qualche giorno lo carico anche sul portale di FabLab Romagna.

Per ora chiudo la issue le restanti informazioni sono prima da validare a livello di associazione, per ora non ho il via libera (eventualmente la riaprirò in futuro).
